/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-2-gff637a7

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD_2nd.h; OD_2nd.c
        Project File: BLVD-KRD-Left.xdd
        File Version: 2

        Created:      2022/03/28 14:27:00
        Created By:   ORIENTAL MOTOR Co., Ltd.
        Modified:     2023/06/08 19:50:25
        Modified By:  ORIENTAL MOTOR Co., Ltd.

    Device Info:
        Vendor Name:  ORIENTAL MOTOR Co., Ltd.
        Vendor ID:    702
        Product Name: BLVD-KRD
        Product ID:   5111

        Description:  EDS for BLVD-KRD
*******************************************************************************/

#ifndef OD_2nd_H
#define OD_2nd_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_2nd_CNT_RPDO 4
#define OD_2nd_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_2nd_CNT_ARR_607B 2
#define OD_2nd_CNT_ARR_607D 2
#define OD_2nd_CNT_ARR_608F 2
#define OD_2nd_CNT_ARR_6091 2
#define OD_2nd_CNT_ARR_6099 2
#define OD_2nd_CNT_ARR_60E3 11
#define OD_2nd_CNT_ARR_60FE 1


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
} OD_2nd_PERSIST_COMM_t;

typedef struct {
    int16_t x402C_directDataOperationOperationDataNumber;
    uint8_t x402D_directDataOperationOperationType;
    int32_t x402E_directDataOperationPosition;
    int32_t x402F_directDataOperationOperatingVelocity;
    int32_t x4030_directDataOperationAccelerationRate;
    int32_t x4031_directDataOperationDecelerationRate;
    int16_t x4032_directDataOperationTorqueLimitingValue;
    int32_t x4033_directDataOperationTrigger;
    uint8_t x4034_directDataOperationForwardingDestination;
    uint32_t x403A_driverInputCommand2nd;
    uint32_t x403C_driverInputCommandAutomaticOFF;
    uint32_t x403E_driverInputCommand;
    int32_t x404B_targetPositionUser_definedPositionUnit;
    uint8_t x40C0_alarmReset;
    uint8_t x40C2_clearAlarmHistory;
    uint8_t x40C5_P_PRESETExecution;
    uint8_t x40C6_configuration;
    uint8_t x40CD_clearLatchInformation;
    uint8_t x40CE_clearSequenceHistory;
    uint8_t x40D0_clearETO;
    uint8_t x40D1_ZSG_PRESET;
    uint8_t x40D2_clearZSG_PRESET;
    uint8_t x40D3_clearInformation;
    uint8_t x40D6_clearUserEnergyConsumption;
    uint8_t x40D7_clearTripmeter0;
    uint8_t x40D8_clearTripmeter1;
    uint8_t x4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates;
    uint16_t x415F_JOG_HOME_TorqueLimitValue;
    uint8_t x4160_HOME_HomingMode;
    uint32_t x4163_HOME_StartingVelocity;
    uint32_t x4169_HOME_BackwardStepsIn2SensorHomeseeking;
    uint16_t x4186_stoppingTimeoutAtAlarmGeneration;
    uint8_t x41CA_WRAPSetting;
    uint32_t x4735_customStoppingRate;
    uint32_t x4736_customStoppingTime;
    uint16_t x6040_controlword;
    int16_t x605A_quickStopOptionCode;
    int16_t x605B_shutdownOptionCode;
    int16_t x605C_disableOperationOptionCode;
    int16_t x605D_haltOptionCode;
    int16_t x605E_faultReactionOptionCode;
    int8_t x6060_modesOfOperation;
    uint32_t x6065_followingErrorWindow;
    uint32_t x6067_positionWindow;
    uint16_t x606D_velocityWindow;
    uint16_t x606F_velocityThreshold;
    uint16_t x6072_maxTorque;
    int32_t x607A_targetPosition;
    uint8_t x607B_positionRangeLimit_sub0;
    int32_t x607B_positionRangeLimit[OD_2nd_CNT_ARR_607B];
    int32_t x607C_homeOffset;
    uint8_t x607D_softwarePositionLimit_sub0;
    int32_t x607D_softwarePositionLimit[OD_2nd_CNT_ARR_607D];
    uint32_t x6081_profileVelocity;
    uint32_t x6082_endVelocity;
    uint32_t x6083_profileAcceleration;
    uint32_t x6084_profileDeceleration;
    uint32_t x6085_quickStopDeceleration;
    uint8_t x608F_positionEncoderResolution_sub0;
    uint32_t x608F_positionEncoderResolution[OD_2nd_CNT_ARR_608F];
    uint8_t x6091_gearRatio_sub0;
    uint32_t x6091_gearRatio[OD_2nd_CNT_ARR_6091];
    int8_t x6098_homingMethod;
    uint8_t x6099_homingSpeeds_sub0;
    uint32_t x6099_homingSpeeds[OD_2nd_CNT_ARR_6099];
    uint32_t x609A_homingAcceleration;
    uint16_t x60B8_touchProbeFunction;
    uint8_t x60E3_supportedHomingMethods_sub0;
    int8_t x60E3_supportedHomingMethods[OD_2nd_CNT_ARR_60E3];
    uint16_t x60F2_positioningOptionCode;
    uint8_t x60FE_digitalOutputs_sub0;
    uint32_t x60FE_digitalOutputs[OD_2nd_CNT_ARR_60FE];
    int32_t x60FF_targetVelocity;
    uint32_t x6502_supportedDriveModes;
    uint32_t x67FE_versionNumber;
    uint32_t x67FF_singleDeviceType;
} OD_2nd_RAM_t;

#ifndef OD_2nd_ATTR_PERSIST_COMM
#define OD_2nd_ATTR_PERSIST_COMM
#endif
extern OD_2nd_ATTR_PERSIST_COMM OD_2nd_PERSIST_COMM_t OD_2nd_PERSIST_COMM;

#ifndef OD_2nd_ATTR_RAM
#define OD_2nd_ATTR_RAM
#endif
extern OD_2nd_ATTR_RAM OD_2nd_RAM_t OD_2nd_RAM;

#ifndef OD_2nd_ATTR_OD
#define OD_2nd_ATTR_OD
#endif
extern OD_2nd_ATTR_OD OD_t *OD_2nd;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_2nd_ENTRY_H1400 &OD_2nd->list[0]
#define OD_2nd_ENTRY_H1401 &OD_2nd->list[1]
#define OD_2nd_ENTRY_H1402 &OD_2nd->list[2]
#define OD_2nd_ENTRY_H1403 &OD_2nd->list[3]
#define OD_2nd_ENTRY_H1600 &OD_2nd->list[4]
#define OD_2nd_ENTRY_H1601 &OD_2nd->list[5]
#define OD_2nd_ENTRY_H1602 &OD_2nd->list[6]
#define OD_2nd_ENTRY_H1603 &OD_2nd->list[7]
#define OD_2nd_ENTRY_H1800 &OD_2nd->list[8]
#define OD_2nd_ENTRY_H1801 &OD_2nd->list[9]
#define OD_2nd_ENTRY_H1802 &OD_2nd->list[10]
#define OD_2nd_ENTRY_H1803 &OD_2nd->list[11]
#define OD_2nd_ENTRY_H1A00 &OD_2nd->list[12]
#define OD_2nd_ENTRY_H1A01 &OD_2nd->list[13]
#define OD_2nd_ENTRY_H1A02 &OD_2nd->list[14]
#define OD_2nd_ENTRY_H1A03 &OD_2nd->list[15]
#define OD_2nd_ENTRY_H402C &OD_2nd->list[16]
#define OD_2nd_ENTRY_H402D &OD_2nd->list[17]
#define OD_2nd_ENTRY_H402E &OD_2nd->list[18]
#define OD_2nd_ENTRY_H402F &OD_2nd->list[19]
#define OD_2nd_ENTRY_H4030 &OD_2nd->list[20]
#define OD_2nd_ENTRY_H4031 &OD_2nd->list[21]
#define OD_2nd_ENTRY_H4032 &OD_2nd->list[22]
#define OD_2nd_ENTRY_H4033 &OD_2nd->list[23]
#define OD_2nd_ENTRY_H4034 &OD_2nd->list[24]
#define OD_2nd_ENTRY_H403A &OD_2nd->list[25]
#define OD_2nd_ENTRY_H403C &OD_2nd->list[26]
#define OD_2nd_ENTRY_H403D &OD_2nd->list[27]
#define OD_2nd_ENTRY_H403E &OD_2nd->list[28]
#define OD_2nd_ENTRY_H403F &OD_2nd->list[29]
#define OD_2nd_ENTRY_H404B &OD_2nd->list[30]
#define OD_2nd_ENTRY_H404C &OD_2nd->list[31]
#define OD_2nd_ENTRY_H404D &OD_2nd->list[32]
#define OD_2nd_ENTRY_H404E &OD_2nd->list[33]
#define OD_2nd_ENTRY_H404F &OD_2nd->list[34]
#define OD_2nd_ENTRY_H4050 &OD_2nd->list[35]
#define OD_2nd_ENTRY_H4056 &OD_2nd->list[36]
#define OD_2nd_ENTRY_H406B &OD_2nd->list[37]
#define OD_2nd_ENTRY_H406C &OD_2nd->list[38]
#define OD_2nd_ENTRY_H406D &OD_2nd->list[39]
#define OD_2nd_ENTRY_H4070 &OD_2nd->list[40]
#define OD_2nd_ENTRY_H4071 &OD_2nd->list[41]
#define OD_2nd_ENTRY_H4072 &OD_2nd->list[42]
#define OD_2nd_ENTRY_H4073 &OD_2nd->list[43]
#define OD_2nd_ENTRY_H4075 &OD_2nd->list[44]
#define OD_2nd_ENTRY_H407A &OD_2nd->list[45]
#define OD_2nd_ENTRY_H407B &OD_2nd->list[46]
#define OD_2nd_ENTRY_H407C &OD_2nd->list[47]
#define OD_2nd_ENTRY_H407D &OD_2nd->list[48]
#define OD_2nd_ENTRY_H407E &OD_2nd->list[49]
#define OD_2nd_ENTRY_H407F &OD_2nd->list[50]
#define OD_2nd_ENTRY_H409B &OD_2nd->list[51]
#define OD_2nd_ENTRY_H409C &OD_2nd->list[52]
#define OD_2nd_ENTRY_H409D &OD_2nd->list[53]
#define OD_2nd_ENTRY_H409E &OD_2nd->list[54]
#define OD_2nd_ENTRY_H409F &OD_2nd->list[55]
#define OD_2nd_ENTRY_H40A1 &OD_2nd->list[56]
#define OD_2nd_ENTRY_H40A2 &OD_2nd->list[57]
#define OD_2nd_ENTRY_H40A3 &OD_2nd->list[58]
#define OD_2nd_ENTRY_H40A4 &OD_2nd->list[59]
#define OD_2nd_ENTRY_H40A9 &OD_2nd->list[60]
#define OD_2nd_ENTRY_H40AA &OD_2nd->list[61]
#define OD_2nd_ENTRY_H40AB &OD_2nd->list[62]
#define OD_2nd_ENTRY_H40C0 &OD_2nd->list[63]
#define OD_2nd_ENTRY_H40C2 &OD_2nd->list[64]
#define OD_2nd_ENTRY_H40C5 &OD_2nd->list[65]
#define OD_2nd_ENTRY_H40C6 &OD_2nd->list[66]
#define OD_2nd_ENTRY_H40CD &OD_2nd->list[67]
#define OD_2nd_ENTRY_H40CE &OD_2nd->list[68]
#define OD_2nd_ENTRY_H40D0 &OD_2nd->list[69]
#define OD_2nd_ENTRY_H40D1 &OD_2nd->list[70]
#define OD_2nd_ENTRY_H40D2 &OD_2nd->list[71]
#define OD_2nd_ENTRY_H40D3 &OD_2nd->list[72]
#define OD_2nd_ENTRY_H40D6 &OD_2nd->list[73]
#define OD_2nd_ENTRY_H40D7 &OD_2nd->list[74]
#define OD_2nd_ENTRY_H40D8 &OD_2nd->list[75]
#define OD_2nd_ENTRY_H4148 &OD_2nd->list[76]
#define OD_2nd_ENTRY_H415F &OD_2nd->list[77]
#define OD_2nd_ENTRY_H4160 &OD_2nd->list[78]
#define OD_2nd_ENTRY_H4163 &OD_2nd->list[79]
#define OD_2nd_ENTRY_H4169 &OD_2nd->list[80]
#define OD_2nd_ENTRY_H4186 &OD_2nd->list[81]
#define OD_2nd_ENTRY_H41CA &OD_2nd->list[82]
#define OD_2nd_ENTRY_H4735 &OD_2nd->list[83]
#define OD_2nd_ENTRY_H4736 &OD_2nd->list[84]
#define OD_2nd_ENTRY_H603F &OD_2nd->list[85]
#define OD_2nd_ENTRY_H6040 &OD_2nd->list[86]
#define OD_2nd_ENTRY_H6041 &OD_2nd->list[87]
#define OD_2nd_ENTRY_H605A &OD_2nd->list[88]
#define OD_2nd_ENTRY_H605B &OD_2nd->list[89]
#define OD_2nd_ENTRY_H605C &OD_2nd->list[90]
#define OD_2nd_ENTRY_H605D &OD_2nd->list[91]
#define OD_2nd_ENTRY_H605E &OD_2nd->list[92]
#define OD_2nd_ENTRY_H6060 &OD_2nd->list[93]
#define OD_2nd_ENTRY_H6061 &OD_2nd->list[94]
#define OD_2nd_ENTRY_H6062 &OD_2nd->list[95]
#define OD_2nd_ENTRY_H6064 &OD_2nd->list[96]
#define OD_2nd_ENTRY_H6065 &OD_2nd->list[97]
#define OD_2nd_ENTRY_H6067 &OD_2nd->list[98]
#define OD_2nd_ENTRY_H606B &OD_2nd->list[99]
#define OD_2nd_ENTRY_H606C &OD_2nd->list[100]
#define OD_2nd_ENTRY_H606D &OD_2nd->list[101]
#define OD_2nd_ENTRY_H606F &OD_2nd->list[102]
#define OD_2nd_ENTRY_H6072 &OD_2nd->list[103]
#define OD_2nd_ENTRY_H6077 &OD_2nd->list[104]
#define OD_2nd_ENTRY_H607A &OD_2nd->list[105]
#define OD_2nd_ENTRY_H607B &OD_2nd->list[106]
#define OD_2nd_ENTRY_H607C &OD_2nd->list[107]
#define OD_2nd_ENTRY_H607D &OD_2nd->list[108]
#define OD_2nd_ENTRY_H6081 &OD_2nd->list[109]
#define OD_2nd_ENTRY_H6082 &OD_2nd->list[110]
#define OD_2nd_ENTRY_H6083 &OD_2nd->list[111]
#define OD_2nd_ENTRY_H6084 &OD_2nd->list[112]
#define OD_2nd_ENTRY_H6085 &OD_2nd->list[113]
#define OD_2nd_ENTRY_H608F &OD_2nd->list[114]
#define OD_2nd_ENTRY_H6091 &OD_2nd->list[115]
#define OD_2nd_ENTRY_H6098 &OD_2nd->list[116]
#define OD_2nd_ENTRY_H6099 &OD_2nd->list[117]
#define OD_2nd_ENTRY_H609A &OD_2nd->list[118]
#define OD_2nd_ENTRY_H60A8 &OD_2nd->list[119]
#define OD_2nd_ENTRY_H60A9 &OD_2nd->list[120]
#define OD_2nd_ENTRY_H60B8 &OD_2nd->list[121]
#define OD_2nd_ENTRY_H60B9 &OD_2nd->list[122]
#define OD_2nd_ENTRY_H60BA &OD_2nd->list[123]
#define OD_2nd_ENTRY_H60BB &OD_2nd->list[124]
#define OD_2nd_ENTRY_H60BC &OD_2nd->list[125]
#define OD_2nd_ENTRY_H60BD &OD_2nd->list[126]
#define OD_2nd_ENTRY_H60D5 &OD_2nd->list[127]
#define OD_2nd_ENTRY_H60D6 &OD_2nd->list[128]
#define OD_2nd_ENTRY_H60D7 &OD_2nd->list[129]
#define OD_2nd_ENTRY_H60D8 &OD_2nd->list[130]
#define OD_2nd_ENTRY_H60E3 &OD_2nd->list[131]
#define OD_2nd_ENTRY_H60F2 &OD_2nd->list[132]
#define OD_2nd_ENTRY_H60F4 &OD_2nd->list[133]
#define OD_2nd_ENTRY_H60FD &OD_2nd->list[134]
#define OD_2nd_ENTRY_H60FE &OD_2nd->list[135]
#define OD_2nd_ENTRY_H60FF &OD_2nd->list[136]
#define OD_2nd_ENTRY_H6502 &OD_2nd->list[137]
#define OD_2nd_ENTRY_H67FE &OD_2nd->list[138]
#define OD_2nd_ENTRY_H67FF &OD_2nd->list[139]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_2nd_ENTRY_H1400_RPDOCommunicationParameter &OD_2nd->list[0]
#define OD_2nd_ENTRY_H1401_RPDOCommunicationParameter &OD_2nd->list[1]
#define OD_2nd_ENTRY_H1402_RPDOCommunicationParameter &OD_2nd->list[2]
#define OD_2nd_ENTRY_H1403_RPDOCommunicationParameter &OD_2nd->list[3]
#define OD_2nd_ENTRY_H1600_RPDOMappingParameter &OD_2nd->list[4]
#define OD_2nd_ENTRY_H1601_RPDOMappingParameter &OD_2nd->list[5]
#define OD_2nd_ENTRY_H1602_RPDOMappingParameter &OD_2nd->list[6]
#define OD_2nd_ENTRY_H1603_RPDOMappingParameter &OD_2nd->list[7]
#define OD_2nd_ENTRY_H1800_TPDOCommunicationParameter &OD_2nd->list[8]
#define OD_2nd_ENTRY_H1801_TPDOCommunicationParameter &OD_2nd->list[9]
#define OD_2nd_ENTRY_H1802_TPDOCommunicationParameter &OD_2nd->list[10]
#define OD_2nd_ENTRY_H1803_TPDOCommunicationParameter &OD_2nd->list[11]
#define OD_2nd_ENTRY_H1A00_TPDOMappingParameter &OD_2nd->list[12]
#define OD_2nd_ENTRY_H1A01_TPDOMappingParameter &OD_2nd->list[13]
#define OD_2nd_ENTRY_H1A02_TPDOMappingParameter &OD_2nd->list[14]
#define OD_2nd_ENTRY_H1A03_TPDOMappingParameter &OD_2nd->list[15]
#define OD_2nd_ENTRY_H402C_directDataOperationOperationDataNumber &OD_2nd->list[16]
#define OD_2nd_ENTRY_H402D_directDataOperationOperationType &OD_2nd->list[17]
#define OD_2nd_ENTRY_H402E_directDataOperationPosition &OD_2nd->list[18]
#define OD_2nd_ENTRY_H402F_directDataOperationOperatingVelocity &OD_2nd->list[19]
#define OD_2nd_ENTRY_H4030_directDataOperationAccelerationRate &OD_2nd->list[20]
#define OD_2nd_ENTRY_H4031_directDataOperationDecelerationRate &OD_2nd->list[21]
#define OD_2nd_ENTRY_H4032_directDataOperationTorqueLimitingValue &OD_2nd->list[22]
#define OD_2nd_ENTRY_H4033_directDataOperationTrigger &OD_2nd->list[23]
#define OD_2nd_ENTRY_H4034_directDataOperationForwardingDestination &OD_2nd->list[24]
#define OD_2nd_ENTRY_H403A_driverInputCommand2nd &OD_2nd->list[25]
#define OD_2nd_ENTRY_H403C_driverInputCommandAutomaticOFF &OD_2nd->list[26]
#define OD_2nd_ENTRY_H403D_NETSelectionDataNumber &OD_2nd->list[27]
#define OD_2nd_ENTRY_H403E_driverInputCommand &OD_2nd->list[28]
#define OD_2nd_ENTRY_H403F_driverOutputStatus &OD_2nd->list[29]
#define OD_2nd_ENTRY_H404B_targetPositionUser_definedPositionUnit &OD_2nd->list[30]
#define OD_2nd_ENTRY_H404C_demandPositionUser_definedPositionUnit &OD_2nd->list[31]
#define OD_2nd_ENTRY_H404D_actualPositionUser_definedPositionUnit &OD_2nd->list[32]
#define OD_2nd_ENTRY_H404E_targetVelocityUser_definedVelocityUnit &OD_2nd->list[33]
#define OD_2nd_ENTRY_H404F_demandVelocityUser_definedVelocityUnit &OD_2nd->list[34]
#define OD_2nd_ENTRY_H4050_actualVelocityUser_definedVelocityUnit &OD_2nd->list[35]
#define OD_2nd_ENTRY_H4056_presentCommunicationError &OD_2nd->list[36]
#define OD_2nd_ENTRY_H406B_torqueMonitor &OD_2nd->list[37]
#define OD_2nd_ENTRY_H406C_loadFactorMonitor &OD_2nd->list[38]
#define OD_2nd_ENTRY_H406D_cumulativeLoadMonitor &OD_2nd->list[39]
#define OD_2nd_ENTRY_H4070_nextDataNumber &OD_2nd->list[40]
#define OD_2nd_ENTRY_H4071_loopOriginDataNumber &OD_2nd->list[41]
#define OD_2nd_ENTRY_H4072_loopCount &OD_2nd->list[42]
#define OD_2nd_ENTRY_H4073_positionDeviation &OD_2nd->list[43]
#define OD_2nd_ENTRY_H4075_speedDeviation &OD_2nd->list[44]
#define OD_2nd_ENTRY_H407A_tripmeter1 &OD_2nd->list[45]
#define OD_2nd_ENTRY_H407B_presentInformation &OD_2nd->list[46]
#define OD_2nd_ENTRY_H407C_driverTemperature &OD_2nd->list[47]
#define OD_2nd_ENTRY_H407D_motorTemperature &OD_2nd->list[48]
#define OD_2nd_ENTRY_H407E_odometer &OD_2nd->list[49]
#define OD_2nd_ENTRY_H407F_tripmeter0 &OD_2nd->list[50]
#define OD_2nd_ENTRY_H409B_mainPowerSupplyCurrent &OD_2nd->list[51]
#define OD_2nd_ENTRY_H409C_powerConsumption &OD_2nd->list[52]
#define OD_2nd_ENTRY_H409D_energyConsumption &OD_2nd->list[53]
#define OD_2nd_ENTRY_H409E_userEnergyConsumption &OD_2nd->list[54]
#define OD_2nd_ENTRY_H409F_totalEnergyConsumption &OD_2nd->list[55]
#define OD_2nd_ENTRY_H40A1_totalUptime &OD_2nd->list[56]
#define OD_2nd_ENTRY_H40A2_numberOfBoots &OD_2nd->list[57]
#define OD_2nd_ENTRY_H40A3_inverterVoltage &OD_2nd->list[58]
#define OD_2nd_ENTRY_H40A4_mainPowerSupplyVoltage &OD_2nd->list[59]
#define OD_2nd_ENTRY_H40A9_continuousUptime &OD_2nd->list[60]
#define OD_2nd_ENTRY_H40AA_RS_485CommunicationReceptionByteCounter &OD_2nd->list[61]
#define OD_2nd_ENTRY_H40AB_RS_485CommunicationTransmissionByteCounter &OD_2nd->list[62]
#define OD_2nd_ENTRY_H40C0_alarmReset &OD_2nd->list[63]
#define OD_2nd_ENTRY_H40C2_clearAlarmHistory &OD_2nd->list[64]
#define OD_2nd_ENTRY_H40C5_P_PRESETExecution &OD_2nd->list[65]
#define OD_2nd_ENTRY_H40C6_configuration &OD_2nd->list[66]
#define OD_2nd_ENTRY_H40CD_clearLatchInformation &OD_2nd->list[67]
#define OD_2nd_ENTRY_H40CE_clearSequenceHistory &OD_2nd->list[68]
#define OD_2nd_ENTRY_H40D0_clearETO &OD_2nd->list[69]
#define OD_2nd_ENTRY_H40D1_ZSG_PRESET &OD_2nd->list[70]
#define OD_2nd_ENTRY_H40D2_clearZSG_PRESET &OD_2nd->list[71]
#define OD_2nd_ENTRY_H40D3_clearInformation &OD_2nd->list[72]
#define OD_2nd_ENTRY_H40D6_clearUserEnergyConsumption &OD_2nd->list[73]
#define OD_2nd_ENTRY_H40D7_clearTripmeter0 &OD_2nd->list[74]
#define OD_2nd_ENTRY_H40D8_clearTripmeter1 &OD_2nd->list[75]
#define OD_2nd_ENTRY_H4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates &OD_2nd->list[76]
#define OD_2nd_ENTRY_H415F_JOG_HOME_TorqueLimitValue &OD_2nd->list[77]
#define OD_2nd_ENTRY_H4160_HOME_HomingMode &OD_2nd->list[78]
#define OD_2nd_ENTRY_H4163_HOME_StartingVelocity &OD_2nd->list[79]
#define OD_2nd_ENTRY_H4169_HOME_BackwardStepsIn2SensorHomeseeking &OD_2nd->list[80]
#define OD_2nd_ENTRY_H4186_stoppingTimeoutAtAlarmGeneration &OD_2nd->list[81]
#define OD_2nd_ENTRY_H41CA_WRAPSetting &OD_2nd->list[82]
#define OD_2nd_ENTRY_H4735_customStoppingRate &OD_2nd->list[83]
#define OD_2nd_ENTRY_H4736_customStoppingTime &OD_2nd->list[84]
#define OD_2nd_ENTRY_H603F_errorCode &OD_2nd->list[85]
#define OD_2nd_ENTRY_H6040_controlword &OD_2nd->list[86]
#define OD_2nd_ENTRY_H6041_statusword &OD_2nd->list[87]
#define OD_2nd_ENTRY_H605A_quickStopOptionCode &OD_2nd->list[88]
#define OD_2nd_ENTRY_H605B_shutdownOptionCode &OD_2nd->list[89]
#define OD_2nd_ENTRY_H605C_disableOperationOptionCode &OD_2nd->list[90]
#define OD_2nd_ENTRY_H605D_haltOptionCode &OD_2nd->list[91]
#define OD_2nd_ENTRY_H605E_faultReactionOptionCode &OD_2nd->list[92]
#define OD_2nd_ENTRY_H6060_modesOfOperation &OD_2nd->list[93]
#define OD_2nd_ENTRY_H6061_modesOfOperationDisplay &OD_2nd->list[94]
#define OD_2nd_ENTRY_H6062_positionDemandValue &OD_2nd->list[95]
#define OD_2nd_ENTRY_H6064_positionActualValue &OD_2nd->list[96]
#define OD_2nd_ENTRY_H6065_followingErrorWindow &OD_2nd->list[97]
#define OD_2nd_ENTRY_H6067_positionWindow &OD_2nd->list[98]
#define OD_2nd_ENTRY_H606B_velocityDemandValue &OD_2nd->list[99]
#define OD_2nd_ENTRY_H606C_velocityActualValue &OD_2nd->list[100]
#define OD_2nd_ENTRY_H606D_velocityWindow &OD_2nd->list[101]
#define OD_2nd_ENTRY_H606F_velocityThreshold &OD_2nd->list[102]
#define OD_2nd_ENTRY_H6072_maxTorque &OD_2nd->list[103]
#define OD_2nd_ENTRY_H6077_torqueActualValue &OD_2nd->list[104]
#define OD_2nd_ENTRY_H607A_targetPosition &OD_2nd->list[105]
#define OD_2nd_ENTRY_H607B_positionRangeLimit &OD_2nd->list[106]
#define OD_2nd_ENTRY_H607C_homeOffset &OD_2nd->list[107]
#define OD_2nd_ENTRY_H607D_softwarePositionLimit &OD_2nd->list[108]
#define OD_2nd_ENTRY_H6081_profileVelocity &OD_2nd->list[109]
#define OD_2nd_ENTRY_H6082_endVelocity &OD_2nd->list[110]
#define OD_2nd_ENTRY_H6083_profileAcceleration &OD_2nd->list[111]
#define OD_2nd_ENTRY_H6084_profileDeceleration &OD_2nd->list[112]
#define OD_2nd_ENTRY_H6085_quickStopDeceleration &OD_2nd->list[113]
#define OD_2nd_ENTRY_H608F_positionEncoderResolution &OD_2nd->list[114]
#define OD_2nd_ENTRY_H6091_gearRatio &OD_2nd->list[115]
#define OD_2nd_ENTRY_H6098_homingMethod &OD_2nd->list[116]
#define OD_2nd_ENTRY_H6099_homingSpeeds &OD_2nd->list[117]
#define OD_2nd_ENTRY_H609A_homingAcceleration &OD_2nd->list[118]
#define OD_2nd_ENTRY_H60A8_SIUnitPosition &OD_2nd->list[119]
#define OD_2nd_ENTRY_H60A9_SIUnitVelocity &OD_2nd->list[120]
#define OD_2nd_ENTRY_H60B8_touchProbeFunction &OD_2nd->list[121]
#define OD_2nd_ENTRY_H60B9_touchProbeStatus &OD_2nd->list[122]
#define OD_2nd_ENTRY_H60BA_touchProbe1PositiveEdge &OD_2nd->list[123]
#define OD_2nd_ENTRY_H60BB_touchProbe1NegativeEdge &OD_2nd->list[124]
#define OD_2nd_ENTRY_H60BC_touchProbe2PositiveEdge &OD_2nd->list[125]
#define OD_2nd_ENTRY_H60BD_touchProbe2NegativeEdge &OD_2nd->list[126]
#define OD_2nd_ENTRY_H60D5_touchProbe1PositiveEdgeCounter &OD_2nd->list[127]
#define OD_2nd_ENTRY_H60D6_touchProbe1NegativeEdgeCounter &OD_2nd->list[128]
#define OD_2nd_ENTRY_H60D7_touchProbe2PositiveEdgeCounter &OD_2nd->list[129]
#define OD_2nd_ENTRY_H60D8_touchProbe2NegativeEdgeCounter &OD_2nd->list[130]
#define OD_2nd_ENTRY_H60E3_supportedHomingMethods &OD_2nd->list[131]
#define OD_2nd_ENTRY_H60F2_positioningOptionCode &OD_2nd->list[132]
#define OD_2nd_ENTRY_H60F4_followingErrorActualValue &OD_2nd->list[133]
#define OD_2nd_ENTRY_H60FD_digitalInputs &OD_2nd->list[134]
#define OD_2nd_ENTRY_H60FE_digitalOutputs &OD_2nd->list[135]
#define OD_2nd_ENTRY_H60FF_targetVelocity &OD_2nd->list[136]
#define OD_2nd_ENTRY_H6502_supportedDriveModes &OD_2nd->list[137]
#define OD_2nd_ENTRY_H67FE_versionNumber &OD_2nd->list[138]
#define OD_2nd_ENTRY_H67FF_singleDeviceType &OD_2nd->list[139]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_2nd_INIT_CONFIG(config) {\
    (config).CNT_NMT = 0;\
    (config).ENTRY_H1017 = NULL;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = 0;\
    (config).ENTRY_H1001 = NULL;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = 0;\
    (config).ENTRY_H1200 = NULL;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_2nd_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_2nd_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_2nd_ENTRY_H1600;\
    (config).CNT_TPDO = OD_2nd_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_2nd_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_2nd_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_2nd_H */
